### PR TITLE
Fix testing for Windows

### PR DESCRIPTION
**Pull request by paulcallen**
# Updates to allow dcos-go to run unittests on Windows

## Checklist
- [X] ~80% unit test coverage?
- [X] Updated [README.md](README.md)?
- [X] Completed sections of this PR template?
- [X] Edited all sections [IN BRACKETS]

## Overview of Change
- Vendor directory would not build on Windows. Blew it away and recreated it on Windows `govendor add +external`, and on Linux `govendor add +missing`
- Disabled TestExpectedBehavior and TestZookeeperPartition unittests for now on Windows due to docker dependency. Once CI is added for this I will work through the problems and re-enable them.
- small change to powershell test script to not delete the vendor directory as it is now checked in.
- A few files also showed up as an error for gofmt so fixed them.

### Changelog [optional]
- [] [optional list]

## Affected Usage
Run tests on Windows using `powershell -file scripts\test.ps1`

### CODE REVIEW

**Comment by collinvandyck** [comment]
@paulcallen what do you mean by `Vendor directory would not build on Windows` ?  Why did the govendor steps you listed solve the problem?

Does this mean that future steps taken to add/manage dependencies using govendor would have to happen in a particular way?

**Comment by paulcallen** [comment]
there were various build errors that I believe were caused by some out-dated windows implementations of dependent packages or bad dependencies. Deleting the .\vendor directory and regenerating them automatically with the above commands solved that. Hopefully this is a one-off situation that will not happen again.

**Comment by collinvandyck** [comment]
Can you detail the specific error(s) you ran into before you made these changes?  Why did you use +external on windows and +missing on linux?

**Comment by paulcallen** [comment]
My understanding is that +external automatically generates the vendor dependencies based on source. To make sure there were no extra Linux dependenies (which it may not of actually had!) I did the +missing. More of a validation phase more than anything.
To be clear, I may be mistaken, but after building on Windows and Linux things seemed to work fine.

Running tests against the current master show these errors:
```
Running tests for github.com/dcos/dcos-go/elector
# golang.org/x/crypto/ssh/terminal
..\..\..\golang.org\x\crypto\ssh\terminal\util_windows.go:44:16: undefined: windows.ENABLE_ECHO_INPUT
..\..\..\golang.org\x\crypto\ssh\terminal\util_windows.go:44:44: undefined: windows.ENABLE_PROCESSED_INPUT
..\..\..\golang.org\x\crypto\ssh\terminal\util_windows.go:44:77: undefined: windows.ENABLE_LINE_INPUT
..\..\..\golang.org\x\crypto\ssh\terminal\util_windows.go:44:105: undefined: windows.ENABLE_PROCESSED_OUTPUT
..\..\..\golang.org\x\crypto\ssh\terminal\util_windows.go:45:12: undefined: windows.SetConsoleMode
..\..\..\golang.org\x\crypto\ssh\terminal\util_windows.go:64:9: undefined: windows.SetConsoleMode
..\..\..\golang.org\x\crypto\ssh\terminal\util_windows.go:69:11: undefined: windows.ConsoleScreenBufferInfo
..\..\..\golang.org\x\crypto\ssh\terminal\util_windows.go:70:12: undefined: windows.GetConsoleScreenBufferInfo
..\..\..\golang.org\x\crypto\ssh\terminal\util_windows.go:86:10: undefined: windows.ENABLE_ECHO_INPUT
..\..\..\golang.org\x\crypto\ssh\terminal\util_windows.go:87:9: undefined: windows.ENABLE_PROCESSED_INPUT
..\..\..\golang.org\x\crypto\ssh\terminal\util_windows.go:87:9: too many errors
FAIL    github.com/dcos/dcos-go/elector [build failed]```

**Comment by collinvandyck** [comment]
In order to reduce the surface area of this changeset, would it be possibly to only update the `golang/org/x/crypto` dependency?  assuming that's the only thing that's causing your windows build to fail...

**Comment by paulcallen** [comment]
it seems to be some confusion between the vendor libraries and the base packages in golang as the errors are not coming from the vendor directory, but they are the ones that seem to be causing it.
I can update `govendor fetch golang.org\x\crypto\ssh\terminal` but the problem does not go away

**Comment by collinvandyck** [comment]
Do you get the same error after updating the crypto lib?  I would prefer to figure out what the exact issue is first.

**Comment by paulcallen** [comment]
my concern is that with now checking in the vendor dependencies it seems some incompatible versions of the packages don't work on Windows, and blowing away the dependencies and recreating them fixes this.. 
The other alternative is to not check in the dependencies, and get them as part of the test script which is now it worked before

**Comment by collinvandyck** [comment]
That's understandable, but do you get the same error after updating the crypto lib?

**Comment by paulcallen** [comment]
Doing this `govendor fetch golang.org/x/sys/windows` made no difference.
Doing this ` go get -u golang.org/x/sys/windows` now creates errors elsewhere:
```Running tests for github.com/dcos/dcos-go/elector
# github.com/dcos/dcos-go/vendor/github.com/docker/docker/pkg/term
vendor\github.com\docker\docker\pkg\term\term_windows.go:13:2: imported and not used: "github.com/dcos/dcos-go/vendor/github.com/docker/docker/pkg/term/windows" as windowsconsole
vendor\github.com\docker\docker\pkg\term\term_windows.go:43:10: undefined: windows
vendor\github.com\docker\docker\pkg\term\term_windows.go:46:10: undefined: windows
vendor\github.com\docker\docker\pkg\term\term_windows.go:52:10: undefined: windows
vendor\github.com\docker\docker\pkg\term\term_windows.go:176:9: undefined: windows
vendor\github.com\docker\docker\pkg\term\term_windows.go:196:9: undefined: windows
FAIL    github.com/dcos/dcos-go/elector [build failed]
```

**Comment by paulcallen** [comment]
for what its worth, other people seem to have had similar problems from doing a web search, and after fixing the dependencies it solves it. Not sure how they solved it though.

**Comment by collinvandyck** [comment]
Hmm ok. I think we want to leave the dependencies vendored (as opposed to fetching them everytime we do a build).  Let's see what the Jenkins build does. I imagine if it passes, then it should be fine. I'll have more time to look into this more thoroughly tomorrow.  Thanks for the PR!

**Comment by collinvandyck** [comment]
test this please

**Comment by paulcallen** [comment]
huh, confused as to why this does not fail on my Linux machine

**Comment by collinvandyck** [comment]
Is github.com/pkg/errors in the vendor directory?

**Comment by collinvandyck** [comment]
ok to test

**Comment by paulcallen** [comment]
huh, the directory was empty. let me push a change to that

**Comment by paulcallen** [comment]
ok, that should do it.  Can we re-run?

**Comment by collinvandyck** [comment]
What command did you use to re-add the missing package?  Also, this is the kind of thing that scares me about these wide-ranging changes.  It would be better if we could figure out what the exact issue is and then solve that.

**Comment by paulcallen** [comment]
I removed and re-added the package: `govendor remove github.com/pkg/errors` followed by `govendor fetch github.com/pkg/errors`. Now the files show up and looks like Jenkins passed.

**Comment by paulcallen** [comment]
I do not like this wide ranging change either, but it seems that some interdependency somewhere was messing with things and there is no easy way of determining what specific thing was broken. The rebuild I believe is actually the safest thing because it went and built the dependencies automatically which should be right.

**Pull request merged**
