### PR TITLE
Use a single vendor directory for the whole repo

### PR DESCRIPTION
**Pull request by rji**
Prior to this commit, a vendor directory existed deep in an example
directory for jwt/transport. This commit relocates it to the root of the
repository so that we can share a single `vendor/` directory across all
packages in dcos-go.

### CODE REVIEW

**Comment by darkonie** [comment]
@rji the vendor folder in example should only be used by that example program. We should not vendor dependencies for our libraries.

**Comment by darkonie** [comment]
Makefile in root is only used by jenkins to run the tests

**Comment by rji** [comment]
I use the Makefile locally to run tests as well. In this particular case, jwt-go was not already in my $GOPATH. Why wouldn't we want to vendor dependencies?

**Comment by darkonie** [comment]
because these are libraries, the one who uses the library must be vendoring.

**Comment by rji** [comment]
@darkonie Ah ok, I see what you're getting at now :) I was approaching this purely from a development perspective. In that case, +1. I'll close this PR. Thanks for giving it a look!

**Pull request closed without merging**
